# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3c65daf5ac3362f2c9333d39756e789a176ce14122ef4ddbf498ce3b15d2786c098d52bf3ade9474682786071eae63ed0f56e63ed9b6501a8b3b72c9029d7185

test:
  secret_key_base: 55c29aa2e6b76fd6d2463b57bd92c0c3cb320bd84cb62bbc6fc41b1c8b2a88b1433c3727b24bb2588041f62d830adc39fc4754ee34fc0a079d3b67f55e088db1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
